name: Package uPersonalize
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    env:
      Configuration: 'Release'
      Output_Folder: './output'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set env release variable
      run: echo "Release_Version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c ${{ env.Configuration }} -o ${{ env.Output_Folder }} /p:Version=${{ env.Release_Version }}
    - name: Upload Nuget Package
      uses: actions/upload-artifact@v2
      with:
        name: uPersonalize-${{ env.Release_Version }}
        path: ${{ env.Output_Folder }}/uPersonalize.${{ env.Release_Version }}.nupkg