name: Package uPersonalize
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    env:
      Configuration: 'Release'
      Output_Folder: './output'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set env release variable
      run: echo "Release_Version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Pack Nuget Package
      run: dotnet pack -c ${{ env.Configuration }} -o ${{ env.Output_Folder }} /p:Version=${{ env.Release_Version }}
    - name: Publish the package to nuget.org
      run: dotnet nuget add source --username agilbert-rba --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/rbaconsulting/index.json"
    - name: Publish the package to nuget.org
      run: dotnet nuget push "${{ env.Output_Folder }}/uPersonalize.${{ env.Release_Version }}.nupkg" --source "github"
    - name: Upload to artifact
      uses: actions/upload-artifact@v2
      with:
        name: uPersonalize-${{ env.Release_Version }}
        path: ${{ env.Output_Folder }}/uPersonalize.${{ env.Release_Version }}.nupkg
