name: Package uPersonalize
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    env:
      Configuration: 'Release'
      Output_Folder: './output'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Set env release variable
      run: echo "Release_Version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x

    - name: Pack Nuget Package
      run: dotnet pack -c ${{ env.Configuration }} -o ${{ env.Output_Folder }} /p:Version=${{ env.Release_Version }}
    
    - name: Add nuget.org package source
      run: dotnet nuget add source --username agilbert-rba --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/rbaconsulting/index.json"
    
    - name: Publish the github packages
      run: dotnet nuget push "${{ env.Output_Folder }}/uPersonalize.${{ env.Release_Version }}.nupkg" --source "github"

    - name: Publish to nuget.org
      run: dotnet nuget push ${{ env.Output_Folder }}/uPersonalize.${{ env.Release_Version }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} -s 'https://api.nuget.org/v3/index.json'

    - name: Upload to artifact
      uses: actions/upload-artifact@v2
      with:
        name: uPersonalize-${{ env.Release_Version }}
        path: ${{ env.Output_Folder }}/uPersonalize.${{ env.Release_Version }}.nupkg